add name to readme
pgomesdev/desenvolve-squad-2 pull request #2
Opened 2022-03-29 23:10 UTC by ValdirAPN

2022-04-08 10:27 UTC, pgomesdev requested changes

2022-04-08 10:27 UTC, pgomesdev commented on README.md
> -## Integrantes
Não remover o nome da seção.

2022-04-11 11:35 UTC, ValdirAPN reviewed
Corrigido

2022-04-18 11:28 UTC, pgomesdev approved these changes

2022-04-18 12:33 UTC, merged